trigger:
  branches:
    include:
    - refs/main/
  paths:
    include:
    - Uev/templates
    - Uev/tests
    - Uev/Publish-Templates.yml

variables:
  AZURE_SUBSCRIPTION: "Visual Studio Enterprise Subscription(ecc20e70-4763-4541-8b32-f28b3d341562)"
  STORAGE_ACCOUNT: "stpydeviceause"

jobs:
- job: push_templates
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    persistCredentials: true

  - task: PowerShell@2
    displayName: "Install Pester"
    inputs:
      targetType: 'inline'
      script: |
        Install-Module -Name "Pester"
      verbosePreference: 'continue'
      pwsh: true
      workingDirectory: '$(Build.SourcesDirectory)'

  - task: PowerShell@2
    displayName: "Validate templates against UE-V schema"
    inputs:
      targetType: 'inline'
      script: |
        Import-Module -Name "Pester" -Force
        $Config = [PesterConfiguration]::Default
        $Config.Run.Path = '$(Build.SourcesDirectory)\Uev\tests'
        $Config.Run.PassThru = $True
        $Config.CodeCoverage.Enabled = $False
        $Config.TestResult.Enabled = $True
        $Config.TestResult.OutputFormat = "NUnitXml"
        $Config.TestResult.OutputPath = ".\TestResults.xml"
        Invoke-Pester -Configuration $Config
      verbosePreference: 'continue'
      pwsh: true
      workingDirectory: '$(Build.SourcesDirectory)\Uev\tests'

  - task: AzureFileCopy@4
    displayName: "Push templates to storage account"
    inputs:
      SourcePath: '$(Build.SourcesDirectory)\Uev\templates'
      azureSubscription: '$(AZURE_SUBSCRIPTION)'
      destination: 'AzureBlob'
      storage: '$(STORAGE_ACCOUNT)'
      containerName: 'uev'
      additionalArgumentsForBlobCopy: '--log-level=INFO'
      copyFilesInParallel: true
      cleanTargetBeforeCopy: false
